name: yml_ecommerce_test
description: A new Flutter setup application for starting a project.

publish_to: 'none'
version: 2.0.9+9
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.2.0
  provider: ^6.0.3
  connectivity_plus: ^5.0.2
  dio: ^5.3.4
  http: ^1.1.1
  shared_preferences: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.0.2
  image_picker: ^1.0.4
  webview_flutter: ^4.4.2
  flutter_html: ^3.0.0-alpha.3
  share_plus: ^7.2.1
  photo_view: ^0.14.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^16.1.0
  path_provider: ^2.0.1
  google_sign_in: ^6.1.6
  flutter_facebook_auth:
  flutter_svg: ^2.0.9
  phone_number: ^2.0.1
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.0
  geocoding: ^2.0.0
  geolocator: ^10.1.0
  flutter_typeahead: ^4.0.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.14.7
  flutter_widget_from_html_core: ^0.14.7
  flutter_html_table: ^3.0.0-alpha.3
  fluttertoast: ^8.0.9
  permission_handler: ^11.1.0
  flutter_downloader: ^1.8.0+1
  country_currency_pickers: ^3.0.0
  dropdown_search: ^5.0.3
  flutter_inappwebview: ^5.7.2+3
  path: ^1.8.2
  cached_network_image: ^3.3.0
  http_parser: ^4.0.2
  intl: ^0.18.0
  sign_in_with_apple: ^5.0.0
  expandable_bottom_sheet: ^1.1.1+1
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  animations: ^2.0.8
  emoji_picker_flutter: ^1.6.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  sqflite: 2.2.7
  just_audio: ^0.9.36
  file_picker: ^6.1.1



dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600


flutter_icons:
  image_path: "assets/images/ymlogo.png"
  android: true
  ios: true


flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: "assets/images/ymlogo.png"

  android_12:
    color: "#FFFFFF"
    image: "assets/images/ymlogo.png"